# Task.FromException method (1 of 2)

Creates a [`Task`](../Task.md) that is completed with a specified exception.

```csharp
public static Task FromException(Exception exception)
```

| parameter | description |
| --- | --- |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [Task](../Task.md)
* namespace [Microsoft.Coyote.Tasks](../Task.md)
* assembly [Microsoft.Coyote](../../Microsoft.Coyote.md)

---

# Task.FromException&lt;TResult&gt; method (2 of 2)

Creates a [`Task`](../Task-1.md) that is completed with a specified exception.

```csharp
public static Task<TResult> FromException<TResult>(Exception exception)
```

| parameter | description |
| --- | --- |
| TResult | The type of the result returned by the task. |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [Task&lt;TResult&gt;](../Task-1.md)
* class [Task](../Task.md)
* namespace [Microsoft.Coyote.Tasks](../Task.md)
* assembly [Microsoft.Coyote](../../Microsoft.Coyote.md)

<!-- DO NOT EDIT: generated by xmldocmd for Microsoft.Coyote.dll -->
